# Generated by Django 3.2.11 on 2024-09-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20240923_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
